# Generated by Django 5.0.3 on 2024-03-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_advuser_send_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='last_name'),
        ),
    ]
